CREATE DATABASE MBMS;

USE MBMS;

CREATE TABLE `ADMIN`(
    ADMIN_ID 			VARCHAR(20) 		PRIMARY KEY,
	PASSWD 				VARCHAR(100)		NOT NULL,
	JOIN_DT 			TIMESTAMP			NOT NULL,
    SELECT_MOVIE		VARCHAR(1)			NOT NULL,
    MANAGEMENT_MOVIE	VARCHAR(1)			NOT NULL,
    SELECT_MEMBER		VARCHAR(1)			NOT NULL,
    MANAGEMENT_MEMBER	VARCHAR(1)			NOT NULL,
    SELECT_COMMENT		VARCHAR(1)			NOT NULL,
    MANAGEMENT_COMMENT	VARCHAR(1)			NOT NULL,
    SELECT_ORDER		VARCHAR(1)			NOT NULL
);

INSERT INTO `ADMIN` VALUES ('master' , 'master97' , NOW(), 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO `ADMIN` VALUES ('jaehyuk' , 'yskhj97' , NOW(), 'N', 'N', 'N', 'N', 'N', 'N', 'N');
INSERT INTO `ADMIN` VALUES ('hyeonkwon' , 'yskjh97' , NOW(), 'N', 'N', 'N', 'N', 'N', 'N', 'N');

CREATE TABLE MEMBER (
    MEMBER_ID 		VARCHAR(20)			PRIMARY KEY,
    PASSWD 			VARCHAR(200)		NOT NULL UNIQUE,	
	MEMBER_NM 		VARCHAR(50)			NOT NULL,
	SEX 			CHAR(1)				NOT NULL,
	BIRTH_DT 		CHAR(10)			NOT NULL, 
	HP 				VARCHAR(13)			NOT NULL,
	SMSSTS_YN 		CHAR(1)				NOT NULL,
	EMAIL 			VARCHAR(30)			NOT NULL,
	EMAILSTS_YN 	CHAR(1)				NOT NULL,
	ZIPCODE 		VARCHAR(10),
	ROAD_ADDRESS 	VARCHAR(200),
	JIBUN_ADDRESS 	VARCHAR(200),
	NAMUJI_ADDRESS 	VARCHAR(200),
	JOIN_DT 		TIMESTAMP			NOT NULL
);

CREATE TABLE MOVIE(
    MOVIE_CD 		  BIGINT 			AUTO_INCREMENT PRIMARY KEY,
    MOVIE_NM 		  VARCHAR(500)		NOT NULL,
    DIRECTOR 		  VARCHAR(200)		NOT NULL,
	RUNNING_TIME 	  VARCHAR(20)		NOT NULL,
	GENRE 			  VARCHAR(20)		NOT NULL,
	RELEASE_DT		  DATE				NOT NULL,
    PLOT			  VARCHAR(2000),
	IMG_NM	  		  VARCHAR(300)		NOT NULL UNIQUE,
    RATINGS			  DOUBLE,
    ORIGINAL_PRICE    INT				NOT NULL,
	ENROLL_DT 		  TIMESTAMP			NOT NULL
);

CREATE TABLE `TICKET`(
	TICKET_CD 			BIGINT 			AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID 			VARCHAR(20)		NOT NULL,
    MOVIE_CD 			BIGINT			NOT NULL,
    MOVIE_NM			VARCHAR(500)	NOT NULL,
	GENRE 			    VARCHAR(20)		NOT NULL,
    ORIGINAL_PRICE		INT				NOT NULL,
    SEAT				VARCHAR(2000)	NOT NULL,
	PAYMENT_AMT			INT				NOT NULL,
	PRICE				INT				NOT NULL,
    PAY_ORDER_TIME 		TIMESTAMP		NOT NULL
);

CREATE TABLE BOARD(
	BOARD_CD 	BIGINT 					PRIMARY KEY AUTO_INCREMENT,
    MOVIE_CD    BIGINT					NOT NULL,    
    MEMBER_ID   VARCHAR(20)				NOT NULL,
   	COMMENT 	VARCHAR(2000)			NOT NULL,
    RATINGS		INT						NOT NULL,
    ENROLL_DT 	TIMESTAMP				NOT NULL
);

CREATE TABLE WISH_LIST(
	WISH_LIST_CD 	BIGINT 				PRIMARY KEY AUTO_INCREMENT,
    MOVIE_CD    	BIGINT				NOT NULL,    
    MEMBER_ID   	VARCHAR(20)			NOT NULL
);